#!/usr/bin/python3
# Python 3 script to create a Markdown document with a list of languages,
# and the contents of .license files.
import os
import glob
import time
from urllib.parse import quote
from datetime import datetime.now as gendate
added_info = """## Looking for Translators

The FreeNT Project is lacking translators, and we need your help. Feel free to add your language ;)

---"""
readme = f"""{added_info}
<!--
   Do not edit this file, it was automatically generated using readme_generate.py!
   Edit the python script to add additional info.

   Generation date (to fix CI errors with git): {gendate()}
-->
# FreeNT OpenWindows License
These are official, localized versions of the OpenWindows license created by the OpenWindows project.
## List of Languages
"""
f = open("readme.md", "w")
for file in sorted(glob.glob("*/*.license")):
  readme = readme + "- [" + os.path.basename(file).split(".")[0] + "](#" + os.path.basename(file).split(".")[0].replace(" ", "-").lower() + ")\n"
readme = readme + "- Not listed? [Submit a language](https://github.com/freent-project/license-translations/issues/new?assignees=&labels=&template=language.yml)!\n"
readme = readme + "## Languages"
for file in sorted(glob.glob("*/*.license")):
  print(file + ":")
  print(open(file, "r").read())
  if os.path.isfile(file.split(".")[0] + ".brl"):
    print("OWL Braille is available in " + os.path.basename(file).split(".")[0] + ". Linking to plain text and braille.")
    readme = readme + "\n### " + os.path.basename(file).split(".")[0] + "\n```\n" + open(file, "r").read() + "```\nAlso available as:\n- [Plain text](/" + quote(file) + ")\n- [Braille (with Unicode Symbols)](/" + quote(file.split(".")[0]) + ".brl" + ")"
  else:
    print("OWL Braille is not available in " + os.path.basename(file).split(".")[0] + ". Linking to plain text only.")
    readme = readme + "\n### " + os.path.basename(file).split(".")[0] + "\n```\n" + open(file, "r").read() + "```\nAlso available as:\n- [Plain text](/" + quote(file) + ")\n- *A braille version is not available for this language.*"
print("Will write README in 3 seconds.")
time.sleep(3)
print("Writing README...")
f.write(readme)
print("Closing connection...")
f.close()
print("Generated and written README!")
