name: Language Request
description: Request a new language
body:
- type: input
  id: language
  attributes:
    label: Language
    placeholder: Please type the full name of the language
  validations:
    required: true
- type: checkboxes
  id: real-language
  attributes:
    label: Requirements
    options:
      - label: I agree that this language belongs to a specific region or ethnic group, and it is not a fictional language.
        required: true
      - label: I agree that any language that does not follow the rules above will be rejected by the translation team.
        required: true
