# This is a basic workflow to help you get started with Actions

name: Anti-PR

# Controls when the workflow will run
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: No Pull Requests
        uses: CodelyTV/no-pull-requests@v1
        with:
         # GitHub token
         GITHUB_TOKEN: ${{ github.token }}
         # Message to show when the pull request is closed
         message: |
            Translations are done by the OpenWindows Team and are not accepted here. Please request a language in Issues.
            
            Adios! ;)
