# This is a workflow to stop PRs from being opened
name: Anti-PR

on:
  pull_request_target:

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close
        uses: superbrothers/close-pull-request@v3.0.0
