name: Generate README

on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run README generator
        run: python readme_generate.py
      - name: Push
        run: |
          git config --global user.email "actions-user@users.noreply.github.com"
          git config --global user.name "actions-user"
          git add .
          git commit -m "Generate README"
          git push
