name: Generate README

on: push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run README generator
        run: python readme_generate.py
      - uses: actions-go/push@master
        with:
          commit-message: 'Generate README'
          remote: origin
